const AURAS = [
    {
        id: 1,
        name: "Anger",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/c/c8/Anger_skill_icon.png",
    },
    {
        id: 2,
        name: "Blood and Sand",
        type: ["stance"],
        reservation: 10,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/0/0f/Blood_and_Sand_skill_icon.png",
    },
    {
        id: 3,
        name: "Clarity",
        type: ["aura"],
        reservation: 279,
        reservationType: "flat",
        icon: "https://www.poewiki.net/w/images/8/8b/Clarity_skill_icon.png",
    },
    {
        id: 4,
        name: "Determination",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/1/14/Determination_skill_icon.png",
    },
    {
        id: 5,
        name: "Discipline",
        type: ["aura"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/d/d7/Discipline_skill_icon.png",
    },
    {
        id: 6,
        name: "Envy",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/1/12/Envy_skill_icon.png",
    },
    {
        id: 7,
        name: "Flesh and Stone",
        type: ["aura", "stance"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/7/71/Flesh_and_Stone_skill_icon.png",
    },
    {
        id: 8,
        name: "Grace",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/b/b3/Grace_skill_icon.png",
    },
    {
        id: 9,
        name: "Haste",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/0/05/Haste_skill_icon.png",
    },
    {
        id: 10,
        name: "Hatred",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/b/b7/Hatred_skill_icon.png",
    },
    {
        id: 11,
        name: "Malevolance",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/5/5c/Malevolence_skill_icon.png",
    },
    {
        id: 12,
        name: "Precision",
        type: ["aura"],
        reservation: 186,
        reservationType: "flat",
        icon: "https://www.poewiki.net/w/images/d/d5/Precision_skill_icon.png",
    },
    {
        id: 13,
        name: "Pride",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/4/47/Pride_skill_icon.png",
    },
    {
        id: 14,
        name: "Purity of Elements",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/0/08/Purity_of_Elements_skill_icon.png",
    },
    {
        id: 15,
        name: "Purity of Fire",
        type: ["aura"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/8/87/Purity_of_Fire_skill_icon.png",
    },
    {
        id: 16,
        name: "Purity of Ice",
        type: ["aura"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/0/07/Purity_of_Ice_skill_icon.png",
    },
    {
        id: 17,
        name: "Purity of Lightning",
        type: ["aura"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/9/96/Purity_of_Lightning_skill_icon.png",
    },
    {
        id: 18,
        name: "Summon Skitterbots",
        type: ["aura"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/1/14/Summon_Skitterbots_skill_icon.png",
    },
    {
        id: 19,
        name: "Vitality",
        type: ["aura"],
        reservation: 233,
        reservationType: "flat",
        icon: "https://www.poewiki.net/w/images/0/05/Vitality_skill_icon.png",
    },
    {
        id: 20,
        name: "Wrath",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/b/bf/Wrath_skill_icon.png",
    },
    {
        id: 21,
        name: "Zealotry",
        type: ["aura"],
        reservation: 50,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/b/bf/Zealotry_skill_icon.png",
    },
]

const BANNERS = [
    {
        id: 22,
        name: "Defiance Banner",
        type: ["banner"],
        reservation: 10,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/9/91/Defiance_Banner_skill_icon.png",
    },
    {
        id: 23,
        name: "Dread Banner",
        type: ["banner"],
        reservation: 10,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/7/7e/Dread_Banner_skill_icon.png",
    },
    {
        id: 24,
        name: "War Banner",
        type: ["banner"],
        reservation: 10,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/9/9f/War_Banner_skill_icon.png",
    },
]

const HERALDS = [
    {
        id: 25,
        name: "Herald of Agony",
        type: ["herald"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/3/3c/Herald_of_Agony_skill_icon.png",
    },
    {
        id: 26,
        name: "Herald of Ice",
        type: ["herald"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/6/6e/Herald_of_Ice_skill_icon.png",
    },
    {
        id: 27,
        name: "Herald of Thunder",
        type: ["herald"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/9/98/Herald_of_Thunder_skill_icon.png",
    },
    {
        id: 28,
        name: "Herald of Ash",
        type: ["herald"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/7/78/Herald_of_Ash_skill_icon.png",
    },
    {
        id: 29,
        name: "Herald of Purity",
        type: ["herald"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/e/eb/Herald_of_Purity_skill_icon.png",
    },
]

const ASPECTS = [
    {
        id: 30,
        name: "Aspect of the Avian",
        type: ["aspect"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/2/2c/Aspect_of_the_Avian_skill_icon.png",
    },
    {
        id: 31,
        name: "Aspect of the Cat",
        type: ["aspect"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/3/3b/Aspect_of_the_Cat_skill_icon.png",
    },
    {
        id: 32,
        name: "Aspect of the Crab",
        type: ["aspect"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/1/14/Aspect_of_the_Crab_skill_icon.png",
    },
    {
        id: 33,
        name: "Aspect of the Spider",
        type: ["aspect"],
        reservation: 25,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/a/a6/Aspect_of_the_Spider_skill_icon.png",
    },
]

const CURSES = [
    {
        id: 34,
        name: "Temporal Chains",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/d/d9/Temporal_Chains_skill_icon.png",
    },
    {
        id: 35,
        name: "Conductivity",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/f/f2/Conductivity_skill_icon.png",
    },
    {
        id: 36,
        name: "Despair",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/9/9e/Despair_skill_icon.png",
    },
    {
        id: 37,
        name: "Elemental Weakness",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/0/04/Elemental_Weakness_skill_icon.png",
    },
    {
        id: 38,
        name: "Enfeeble",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/6/65/Enfeeble_skill_icon.png",
    },
    {
        id: 39,
        name: "Flammability",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/2/2f/Flammability_skill_icon.png",
    },
    {
        id: 40,
        name: "Frostbite",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/e/e7/Frostbite_skill_icon.png",
    },
    {
        id: 41,
        name: "Punishment",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/c/c7/Punishment_skill_icon.png",
    },
    {
        id: 41,
        name: "Vulnerability",
        type: ["curse"],
        reservation: 35,
        reservationType: "percent",
        icon: "https://www.poewiki.net/w/images/4/48/Vulnerability_skill_icon.png",
    },
]

const ALL_AURAS = [...AURAS, ...HERALDS, ...BANNERS, ...ASPECTS, ...CURSES]

export default ALL_AURAS
